#!/bin/bash          

function init_dir {
  echo "Please enter your user account:"
  read TEACHER_ACCOUNT

  echo "Please enter student account, use ; as delimiter"
  read STUDENT_ACCOUNTS

  # init user by adding user to new group
  sudo groupadd -f teacher
  sudo usermod -a -G teacher $TEACHER_ACCOUNT

  # init dirs
  mkdir -p ~/assignments
  chown :teacher ~/assignments
  chmod 075 ~/assignments

  # setgid bit, so all new folders within automatically inherit group 
  chmod g+s ~/assignments

  # create dirs for all students, TODO check for existence account
  export IFS=";" # configure ; as the new delimiter
  for STUDENT_ACCOUNT in $STUDENT_ACCOUNTS; do
    mkdir -p ~/assignments/$STUDENT_ACCOUNT
    chown $STUDENT_ACCOUNT ~/assignments/$STUDENT_ACCOUNT
  done
}

function lock_down {
  chmod 070 -R ~/assignments/*
}

function unlock { 
  chmod 770 -R ~/assignments/*
}